### ISSUE TITLE
Cityscape-Foggy cityscape

### ISSUE THREAD

**Issue by GiovanniPasq** [tiancity-NJU/da-faster-rcnn-PyTorch#25]
Hi, thanks for your work. The cityscape dataset downloadable from the link drive was genereted using the script ["prepare_data.m"](https://github.com/yuhuayc/da-faster-rcnn/blob/master/prepare_data/prepare_data.m) of the original paper author?

**Comment by mochaojie** [comment]
> Hi, thanks for your work. The cityscape dataset downloadable from the link drive was genereted using the script ["prepare_data.m"](https://github.com/yuhuayc/da-faster-rcnn/blob/master/prepare_data/prepare_data.m) of the original paper author?

Do you have the cityscape dataset? Could you share it with me?  My email:810375129@qq.com.  Thank you!

**Comment by kinredon** [comment]
@mochaojie you could apply it from the officials since we don't have the right to distribute.
