### ISSUE TITLE
Dataset Structure

### ISSUE THREAD

**Issue by ShifuShen** [tiancity-NJU/da-faster-rcnn-PyTorch#3]
I download the dataset in https://www.cityscapes-dataset.com/ . The Image zip is leftImg8bit_trainvaltest.zip and the annotations file is gtFine_trainvaltest.zip. However the format of annotations is .json and how can I convert the json annotations to xml annotations before using the code?

**Comment by tiancity-NJU** [comment]
The xml annotations is same as Pascal_VOC. you can process it by this paper official implementation [https://github.com/yuhuayc/da-faster-rcnn/blob/master/prepare_data/prepare_data.m](url).  bacause my matlab version is different with the requirement. so I just do it by my own code but the output is similar. you also could google how to transfer json to pascal_VOC format.

**Comment by ShifuShen** [comment]
@tiancity-NJU got it, thanks~
