### ISSUE TITLE
细节询问

### ISSUE THREAD

**Issue by Angzz** [tiancity-NJU/da-faster-rcnn-PyTorch#7]
你好,看你的代码发现target貌似用到了[gt的信息](https://github.com/tiancity-NJU/da-faster-rcnn-PyTorch/blob/master/lib/model/da_faster_rcnn/faster_rcnn.py#L141),而原文中说是不用gt的,请问是否实现有误?还是说我的理解有误,请不吝赐教!

**Comment by duang33** [comment]
> 你好,看你的代码发现target貌似用到了[gt的信息](https://github.com/tiancity-NJU/da-faster-rcnn-PyTorch/blob/master/lib/model/da_faster_rcnn/faster_rcnn.py#L141),而原文中说是不用gt的,请问是否实现有误?还是说我的理解有误,请不吝赐教!

我也想问，请问您解决这个疑问了吗
